import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1E293B",
    justifyContent: "center",
    alignItems: "center",
  },
  textTitle: {
    color: "#E2E8F0",
    fontSize: 35,
    fontWeight: "bold",
    marginTop: 30,
  },
  card: {
    backgroundColor: "#0F172A",
    borderRadius: 20,
    width: 280,
    height: 500,
    borderWidth: 2,
    justifyContent: "space-between",
    alignItems: "center",
  },
  titulo: {
    color: "#E2E8F0",
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "center",
  },

  prazo: {
    color: "#94A3B8",
    fontSize: 15,
  },
  importancia: {
    fontSize: 20,
    fontWeight: "bold",
    marginTop: 6,
    alignSelf: "center",
  },
  rowRadio: {
    width: "100%",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    height: "10%",
    // borderWidth: 1,
  },
  infoTask: {
    gap: 20,
    height: "65%",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    padding: 4,
    color: "white",
    // borderWidth: 1,
  },
  viewButtons: {
    width: "100%",
    justifyContent: "flex-start",
    alignItems: "center",
    height: "25%",
    // borderWidth: 1,
  },
  btn: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1E293B",
    height: 40,
    borderRadius: 12,
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    borderColor: "#ffffff",
    width: "50%",
    justifyContent: "center",
  },
  textBTN: {
    color: "white",
    fontSize: 20,
    fontWeight: "600",
  },
  input: {
    backgroundColor: "#1E293B",
    width: "90%",
    height: 150,
    fontSize: 17,
    fontWeight: "700",
  },
});
