import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1E293B",
    alignItems: "center",
    paddingTop: 60,
  },
  title: {
    color: "#ffffff",
    fontSize: 30,
    fontWeight: "700",
  },
  divForms: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    padding: 5,
    maxHeight: "100%",
  },
  row: {
    alignItems: "center",
    flexDirection: "row",
    width: "100%",
    justifyContent: "center",
  },
  textTitle: {
    color: "white",
    fontSize: 20,
    fontWeight: "800",
  },
  Textoptions: {
    marginLeft: 8,
    fontSize: 18,
    fontWeight: "600",
    color: "#64748B",
  },
  forms: {
    width: "100%",
    margin: 10,
    gap: 20,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 40,
  },
  btnCalendar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1E293B",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 12,
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    marginTop: 10,
  },
  textCalendario: {
    fontSize: 16,
    color: "#E2E8F0",
    fontWeight: "600",
  },
  radioGroup: {
    width: "100%",
    paddingHorizontal: 20,
    marginTop: 10,
    gap: 10,
  },
  radioCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderWidth: 2,
    borderRadius: 12,
    backgroundColor: "#1E293B",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 10,
  },
  radioLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "#ffffff",
  },
  btnAdd: {
    marginTop: 30,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1E293B",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 12,
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,

    borderColor: "#ffffff",
  },
});
